### ISSUE TITLE
No update on screen - only first frame is received

### ISSUE THREAD

**Issue by fernandobhz** [T1T4N/NVNC#6]
Hi!

I only can get the first frame, i can send mouse commands but, the screen never get update.

Windows 8

**Comment by fernandobhz** [comment]
The version on codeplex is working for me.... only that github version not working

**Comment by T1T4N** [comment]
Hi,
I am sorry for not replying, but I'm very busy with my exams.
You are having problems because the code on GitHub currently uses an experimental class I wrote for handling changes in the screen areas. I am sorry that I didn't properly branch the code and this ended up in the master branch although it's in a test phase. The class is ScreenHandler, which uses QuadNode and QuadTree.
To stop using the experimental code please edit the code in method DoFrameBufferUpdate in VncHost.cs:
Replace (or comment) the lines 587-597 with the following code:

``` cs
EncodedRectangle localRect = factory.Build(new Rectangle2(x,y,width, height), GetPreferredEncoding());
localRect.Encode();
rectangles.Add(localRect);
```

As soon as I finish with my exams and get a little free time, I will organize the code, branch it properly and fix any other issues.
Please stay tuned, I haven't abandoned the project :)

**Comment by fernandobhz** [comment]
It's working now!!!

Thanks.

**Comment by dhilgarth** [comment]
> Please stay tuned, I haven't abandoned the project :)

Is this still true? :-)
